### PR TITLE
FORGOTIYO🤣

### PR DESCRIPTION
**Pull request by MR-JINN-OF-TG**

### CODE REVIEW

**Comment by Oxidisedman** [comment]
Ofcourse! 
I'm busy man I will Fix as soon as possible 🙂
Time⌛nahi to waste.

**Comment by Oxidisedman** [comment]
O is capital letters 😁

**Comment by MR-JINN-OF-TG** [comment]
CLOSING REQUEST

**Comment by Oxidisedman** [comment]
Uff 😆

**Pull request closed without merging**
